CREATE TABLE IF NOT EXISTS `course` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '课程 ID',
    `course_name` VARCHAR(128) NOT NULL COMMENT '课程名称',
    `course_code` VARCHAR(64) NULL COMMENT '课程代码',
    `major` VARCHAR(128) NULL COMMENT '所属专业',
    `grade` VARCHAR(32) NULL COMMENT '年级',
    `total_hours` INT NOT NULL DEFAULT 0 COMMENT '总学时',
    `theory_hours` INT NULL COMMENT '理论学时',
    `experiment_hours` INT NULL COMMENT '实验学时',
    `weekly_hours` INT NULL COMMENT '周学时',
    `credit` DECIMAL(4,1) NULL COMMENT '学分',
    `textbook` VARCHAR(255) NULL COMMENT '教材',
    `course_goal` TEXT NULL COMMENT '课程目标',
    `key_point` TEXT NULL COMMENT '教学重点',
    `difficult_point` TEXT NULL COMMENT '教学难点',
    `assessment_method` TEXT NULL COMMENT '考核方式',
    `syllabus` LONGTEXT NULL COMMENT '课程大纲',
    `description` TEXT NULL COMMENT '课程简介',
    `status` VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT 'ACTIVE / ARCHIVED',
    `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    KEY `idx_course_name` (`course_name`),
    KEY `idx_course_code` (`course_code`),
    KEY `idx_course_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='课程';
