CREATE TABLE IF NOT EXISTS `generate_task` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '生成任务 ID',
    `owner_user_id` BIGINT NOT NULL COMMENT '所属用户 ID',
    `task_type` VARCHAR(32) NOT NULL COMMENT '任务类型：TEACHING_PLAN / TEACHING_CALENDAR / OTHER',
    `task_name` VARCHAR(128) NOT NULL COMMENT '任务名称',
    `course_id` BIGINT NULL COMMENT '课程 ID',
    `class_id` BIGINT NULL COMMENT '班级 ID',
    `semester_id` BIGINT NULL COMMENT '学期 ID',
    `template_id` BIGINT NULL COMMENT '模板 ID',
    `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING / RUNNING / SUCCESS / FAILED',
    `input_json` JSON NULL COMMENT '输入快照',
    `result_summary` VARCHAR(500) NULL COMMENT '结果摘要',
    `failure_reason` VARCHAR(500) NULL COMMENT '失败原因',
    `started_time` DATETIME NULL COMMENT '开始时间',
    `finished_time` DATETIME NULL COMMENT '完成时间',
    `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    PRIMARY KEY (`id`),
    KEY `idx_generate_task_owner` (`owner_user_id`),
    KEY `idx_generate_task_type` (`task_type`),
    KEY `idx_generate_task_status` (`status`),
    KEY `idx_generate_task_created_time` (`created_time`),
    CONSTRAINT `fk_generate_task_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `user` (`id`),
    CONSTRAINT `fk_generate_task_course` FOREIGN KEY (`course_id`) REFERENCES `course` (`id`),
    CONSTRAINT `fk_generate_task_class` FOREIGN KEY (`class_id`) REFERENCES `class_info` (`id`),
    CONSTRAINT `fk_generate_task_semester` FOREIGN KEY (`semester_id`) REFERENCES `semester` (`id`),
    CONSTRAINT `fk_generate_task_template` FOREIGN KEY (`template_id`) REFERENCES `template_file` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='生成任务';
