server:
  port: 8080

spring:
  application:
    name: simon-workspace-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  servlet:
    multipart:
      max-file-size: ${APP_MAX_FILE_SIZE:20MB}
      max-request-size: ${APP_MAX_REQUEST_SIZE:30MB}

management:
  endpoints:
    web:
      exposure:
        include: health,info
