server:
  port: 8080

spring:
  application:
    name: simon-workspace-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      exposure:
        include: health,info
